name: Run and Upload Braille

on: [push, workflow_dispatch]

jobs:
  braille:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install pillow[all] numpy
      - run: python main.py
      - uses: actions/upload-artifact@v4
        with:
          name: braille-output
          path: |
            braille_output.txt
            *.txt
