name: Create Braille Frames
on: [push, workflow_dispatch]
jobs:
  create-frames:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install pillow numpy opencv-python
      - run: python v2ba.py
      - uses: actions/upload-artifact@v4
        with:
          name: frames
          path: frames/
